source :gemcutter

# Gems required by the Picky client.
#
gem 'picky-client', '~> 4.0'
gem 'i18n'
gem 'activesupport', :require => 'active_support/core_ext'
gem 'sinatra'
gem 'haml'
gem 'magic-cards', '0.1.1'
gem 'mana-symbols', '0.1.1'

group :development do
  gem 'sinatra-reloader'
  gem 'pry'
end
