source :gemcutter

# Gems required by the Picky client.
#
gem 'picky-client', '~> 4.0'
gem 'i18n'
gem 'activesupport', :require => 'active_support/core_ext'
gem 'sinatra'
gem 'haml'
gem 'magic-cards'

group :development do
  gem 'sinatra-reloader'
end
