require 'picky-client/tasks'

require 'rspec'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new :spec

# Pass in location of your javascript files, default is "javascripts".
#
Picky::Tasks::Javascripts.new
